config/routes.rb
Rails.application.routes.draw do
 
  get 'user',:to=>'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'manageplayers/filter'
  post 'manageplayers/sort'
  get 'manageplayers/search'
  get 'manageplayers/download'
  get 'manageplayers/sort_by_tot_rushing_yards'
  get 'manageplayers/sort_by_tot_longest_rush'
  get 'manageplayers/sort_by_tot_rushing_touch_downs'
  get 'manageplayers/sort_by_all_three'
  get 'users/show'
  resources :manageplayers, only: [:index,:show] 

  resources :users, only: [:new,:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

def self.to_csv
	CSV.generate do |csv|
		csv<< column_names
		all.each do |player|
			csv << player.attributes.values_at(*column_names)
		end
	end

end

scope :find_player_by_name, ->(name){where(["Player LIKE ?","%#{name}%"])}

end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
 
 EMAIL_FORMAT =  /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
 PASSWORD_FORMAT = /\A
  (?=.{8,})         
  (?=.*\d)          
  (?=.*[a-z])       
  (?=.*[A-Z])        
  (?=.*[[:^alnum:]]) 
/x

 validates :username, :presence=>true,
 					  :length=> {:maximum=>50},
 					  :uniqueness=>true

 validates :password, :presence=>true,
 					  :length=>{:maximum=>50},
 					  :format=>{:with=>PASSWORD_FORMAT}
 
  validates :email, :presence=>true,
				    :uniqueness=>true,
				    :length=>{:maximum=>30},
				    :format=>{:with=>EMAIL_FORMAT}	
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  	before_action :confirm_logged_in, :except=>[:login,:attempt_login,:logout]	
  def menu
  end

  def login
  end

  def attempt_login
  	puts params[:username]
  	if(params[:username].present? && params[:password].present?)
  		found_user = User.where(:username=>params[:username]).first
  		if found_user
		 autherized_user = found_user.authenticate(params[:password])
		end
	end
	 if autherized_user
	    session[:user_id]= autherized_user.id
	 	session[:username] = autherized_user.first_name.to_s+" "+autherized_user.last_name.to_s
	 	logger.info("*** User #{session[:username]} Logged in ****") 
	  	flash[:notice]="You are now logged in. "
	  	redirect_to(user_path)
	  else
	  	flash.now[:notice]="Invalid Username/Password"
	  	render('login')
	  end	
  end

  def logout
  		logger.info("*** User #{session[:username]} Logged out ****")
  		session[:user_id]=nil
  		session[:username]=nil
  		flash[:notice]='Logged out'
  		redirect_to(access_login_path)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
layout "application"

  private

  def confirm_logged_in
    unless session[:user_id]
     flash[:notice]="Please Login first"
     redirect_to(access_login_path)
    end
   end
end

app/controllers/manageplayers_controller.rb
class ManageplayersController < ApplicationController
  def index
  	@player =	Player.paginate(:page => params[:page], :per_page => 4)

  end

  def show
  end

  def filter 

  end
  def sort_by_tot_rushing_yards
  	@player = Player.order("Yds desc").paginate(:page => params[:page], :per_page => 4)
  	download_csv(Player.order("Yds desc"))
  	logger.info("*** CSV file is downloaded for sort_by_tot_rushing_yards ****")
  end

  def sort_by_tot_longest_rush
	@player = Player.order("cast(Lng as signed) desc").paginate(:page => params[:page], :per_page => 4)
 	download_csv(Player.order("cast(Lng as signed) desc"))
   	logger.info("*** CSV file don for sort_by_tot_longest_rush ****")
   end

   def sort_by_tot_rushing_touch_downs
  	@player = Player.order("TD desc").paginate(:page => params[:page], :per_page => 4)
  	download_csv(Player.order("TD desc"))
   	logger.info("CSV file don for sort_by_tot_rushing_touch_downs")
   end

   def sort_by_all_three
   	@player = Player.order("cast(Lng as signed) desc,Yds desc,TD desc").paginate(:page => params[:page], :per_page => 4)
 	download_csv(Player.order("cast(Lng as signed) desc,Yds desc,TD desc"))
 	logger.info("CSV file don for sort_by_all_three")
   end

  def search
 		@player = Player.find_player_by_name(params[:search].to_s.humanize).paginate(:page => params[:page], :per_page => 4)
		if !@player.present?
			flash[:notice] ="No Matching Player"
			redirect_to(manageplayers_path)
		end 
  end

  def download
  	download_csv(Player.find_player_by_name(params[:search].to_s.humanize))
  	logger.info("CSV file downloaded for search results")
  end


  
  private

  	def download_csv(name)
  	  respond_to do |format|
      format.html
      format.csv { 
      send_data name.to_csv,
      filename: "export_#{Time.now}.csv",
      type: 'text/csv; charset=utf-8' 
      }
	  end
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(session[:user_id])
  end

  def new
  	@user = User.new
  end
  def create
	@user = User.new(user_params)
    if(@user.save)
       flash[:notice]="Profile created successfully!!! Please Login..!"
       logger.info("****New User is created ..!!!****")
       redirect_to(access_login_path)
    else
      render 'new'
    end

  end
 

  private 

  def user_params
  	 params.require(:user).permit(:first_name,:last_name,:email,:username,:password)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def error_messages_for(object)
	render(:partial=>'application/error_messages',:locals=>{:object=>object})
end

end

app/helpers/manageplayers_helper.rb
module ManageplayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				
			</div>
			<div class="card-body">
				<%= form_tag(access_attempt_login_path,:method=>:post) do %>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>

						<%= text_field_tag(:username,params[:username], :placeholder=>"Username",:class=>"form-control")%>
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						
						<%= password_field_tag(:password,params[:password], :placeholder=>"Password",:class=>"form-control")%>
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<%= submit_tag("Submit",:class=>"btn float-right login_btn")%>
					</div>
				<% end %>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<%= link_to("Sign Up",new_user_path)%></a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/access/menu.html.erb
<div>
	
<div class="container-fluid p-3 bg-dark text-white">
	<h1 align="center">My Test Application</h1>
<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
	<div class="container adm">
		<h2 align="center"> Menu</h2>
	
		
		<table class="table table-hover menu">
		<tr align="center">
		   <td>
			<%= link_to("List Players",manageplayers_path)%></td></tr>
		
		<tr align="center"><td>
			<%= link_to("Sort Players by Tot Rushing Yards",manageplayers_sort_by_tot_rushing_yards_path)%></td></tr>
		
		<tr align="center"><td>
			<%= link_to("Sort Players by Longest Rush",manageplayers_sort_by_tot_longest_rush_path)%></td></tr>

		<tr align="center"><td>
			<%= link_to("Sort Players by Tot Rushing Tochdowns",manageplayers_sort_by_tot_rushing_touch_downs_path)%></td></tr>
		<tr align="center"><td>
			<%= link_to("Sort Players by Above Three",manageplayers_sort_by_all_three_path)%></td></tr>
		<tr align="center"><td>
			<%= link_to("Show User Profile",:controller=>'users',:action=>'show')%>
		</td></tr>
		 <tr align="center"><td>
			<%= link_to("Logout",access_logout_path)%>
		</td></tr>
		</table>
		
	 </div>


<footer id="footer">
 <div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/application/_error_messages.html.erb
<% if(object && object.errors.size >0 )%>
<div id="error-explanation">
	<h2><%= pluralize(object.errors.size,"error")%>Prohibited this record being saved</h2>
	<p>There were problems with following fields:</p>
	<ul>
		<% object.errors.full_messages.each do |msg|%>
		<li><%= msg%></li>
		<%end%>
	</ul>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsicareer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="flash_notice">
   <% if !flash[:notice].blank?%>
      <div class="alert alert-success flash_div">
        <%= flash[:notice]%>
      </div>
    <%end%>
</div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/manageplayers/_list_players.html.erb
			

			<tr>
		  		<td><%=player.Player%></td>
		  		<td><%=player.Team%></td>
		  		<td><%= player.Pos%></td>
		  		<td><%=player.send("Att/G") %></td>
		  		<td><%= player.Att %></td>
		  		<td><%=player.Yds %></td>
		  		<td><%= player.Avg %></td>
		  		<td><%=player.send("Yds/G") %></td>
		  		<td><%= player.TD %></td>
		  		<td><%=player.Lng %></td>
		  		<td><%= player.send("1st") %></td>
		  		<td><%=player.send("1st%") %></td>
		  		<td><%= player.send("20+") %></td>
		  		<td><%=player.send("40+") %></td>
		  		<td><%= player.FUM %></td>
		  		
		  		
		  </tr>

app/views/manageplayers/index.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_download_path(request.params.merge(format: "csv")))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Attempts</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
		  
		  <%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/manageplayers/search.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_download_path(request.params.merge(format: "csv")))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
			<%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/manageplayers/sort_by_all_three.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_sort_by_all_three_path(format: "csv"))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Attempts</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
		  	<%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/manageplayers/sort_by_tot_longest_rush.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_sort_by_tot_longest_rush_path(format: "csv"))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Attempts</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
		  	<%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/manageplayers/sort_by_tot_rushing_touch_downs.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_sort_by_tot_rushing_touch_downs_path(format: "csv"))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Attempts</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
		  	<%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/manageplayers/sort_by_tot_rushing_yards.html.erb
<div id="con">
	
<div class="container-fluid p-3 bg-dark text-white head">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%><%= link_to("<download as csv>",manageplayers_sort_by_tot_rushing_yards_path(format: "csv"))%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
<div>
<%= form_tag(manageplayers_search_path,:method=>'get') do %>
		<div class="input-group">  
    	<%= search_field_tag :search  %>  
    	<div class='btn btn-info glyphicon glyphicon-search'>  
     
		<%= submit_tag("Search") %>
		</div>
		</div>		
<% end %>
</div>
<div >
	<table class="table table-hover menu">
		<thead class="tb_header">
		  <tr>
		  		<th>Player</th>
		  		<th>Team</th>
		  		<th>Pos</th>
		  		<th>Attempt/Game</th>
		  		<th>Attempts</th>
		  		<th>Yards</th>
		  		<th>Average</th>
		  		<th>Yards/Game</th>
		  		<th>Total Rushing Touchdowns</th>
		  		<th>Longest Rush</th>
		  		<th>Rushing First Downs</th>
		  		<th>Rushing First Downs %</th>
		  		<th>Rushing 20+ Yards Each</th>
		  		<th>Rushing 40+ Yards Each</th>
		  		<th>Rushing Fumbles</th>
		  		<th> </th>
		  </tr>	
		</thead>
		  <% @player.each do |player|%>
		  	<%= render(:partial=>'list_players',:locals=>{:player=>player})%>
		  <%end%>
		</table>
		
</div>
<%= will_paginate @player%>
<footer id="footer">	
<div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>

app/views/users/_form.html.erb
	<%= error_messages_for(f.object)%>

	<table class="table table-striped">
		
			<tr>
				<td><%= f.label("First Name")%></td><td><%=f.text_field(:first_name)%></td>
			</tr>
			<tr>
				<td><%= f.label("Last Name")%></td><td><%=f.text_field(:last_name)%></td>
			</tr>
			<tr>
				<td><%= f.label("User Name")%></td><td><%=f.text_field(:username)%></td>
			</tr><tr>
			<tr>
				
				<td><%= f.label("Email")%></td><td><%=f.text_field(:email)%></td>
			</tr>	
				
				<td><%= f.label("Password")%></td><td><%=f.text_field(:password)%></td>
			</tr>	
				
			
			
	</table> 

app/views/users/new.html.erb
<div id="con">
<div class="container-fluid p-3 bg-dark text-white ">
	<h1 align="center">My Test Application</h1>

		
</div>
<div>

</div>

<div class="container">
	<h2 align="center">Sign Up </h2>
 <%= form_for(@user) do |f|%>
  <%= render(:partial=>'form',:locals=>{:f=>f})%>
  <div class="justify-content-center" align="center">
		<%=f.submit("Create")%>
  </div>
	 	
<% end%>
</div>
<footer id="footer">
  <div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>	

app/views/users/show.html.erb
<div>
<div class="container-fluid p-3 bg-dark text-white">
	<h1 align="center">My Test Application</h1>
	<%= link_to("<Home>",:controller=>'access',:action=>'menu')%>
		<div class="container admin_color" align="right">Logged in as :<%=session[:username]%>  </div>
</div>
]
<div class="container">
	<table class="table table-striped menu">
		<thead>
			<tr> 
				<th>First Name    :</th><th><%= @user.first_name%></th>
			</tr>
			<tr>
				<th>Last Name</th><th><%= @user.last_name%></th>
			</tr>
			<tr>
				<th>User Name</th><th><%= @user.username%></th>
			</tr>	
			<tr>
				<th>Email</th> <th><%= @user.email %></th>
			</tr>
			<tr>
				<th>Created At</th> <th><%= @user.created_at.strftime("%b %d %Y, %H:%M") %></th>
			</tr>
			<tr>
				<th>Updated At</th> <th><%= @user.updated_at.strftime("%b %d %Y, %H:%M") %></th>
			</tr>

		</thead>	
	</table>

</div>
<footer id="footer">
  <div id="footer-content foo">c.nibi123@gmail.com</div>
</footer>
</div>